services:
  app:
    build:
      context: ./src
      dockerfile: ./build/Dockerfile
    container_name: app
    hostname: app
    restart: on-failure
    env_file:
      - src/build/.env
    environment:
      POSTGRES_HOST: postgres
    networks:
      - proxy_net
    links:
      - postgres
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    env_file:
      - ./postgres/.env
    networks:
      - proxy_net
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


volumes:
  postgres:

networks:
  proxy_net:
    name: proxy_net
    driver: bridge
